import { CarFront, Truck } from 'lucide-react';
import type { RaceEvent } from '@/types';

export const raceData: RaceEvent[] = [
  {
    id: 'tc',
    category: 'TC',
    categoryFullName: 'Turismo Carretera',
    Icon: CarFront,
    circuitName: 'Autódromo Rosamonte',
    location: 'Posadas, Misiones',
    date: '2024-07-07T13:30:00-03:00',
    schedule: [
      { day: 'Viernes', activity: 'Entrenamientos', time: '10:00 - 17:00' },
      { day: 'Sábado', activity: 'Clasificación', time: '15:00 - 16:00' },
      { day: 'Domingo', activity: 'Final', time: '13:30' },
    ],
    circuitImage: 'https://placehold.co/600x400.png',
    circuitImageHint: 'race track',
  },
  {
    id: 'tcp',
    category: 'TCP',
    categoryFullName: 'TC Pista',
    Icon: CarFront,
    circuitName: 'Autódromo San Nicolás Ciudad',
    location: 'San Nicolás, Buenos Aires',
    date: '2024-07-28T12:10:00-03:00',
    schedule: [
      { day: 'Viernes', activity: 'Entrenamientos', time: '09:00 - 16:00' },
      { day: 'Sábado', activity: 'Clasificación', time: '14:00 - 15:00' },
      { day: 'Domingo', activity: 'Final', time: '12:10' },
    ],
    circuitImage: 'https://placehold.co/600x400.png',
    circuitImageHint: 'asphalt circuit',
  },
  {
    id: 'tcm',
    category: 'TCM',
    categoryFullName: 'TC Mouras',
    Icon: CarFront,
    circuitName: 'Autódromo Roberto Mouras',
    location: 'La Plata, Buenos Aires',
    date: '2024-08-18T13:00:00-03:00',
    schedule: [
      { day: 'Viernes', activity: 'Entrenamientos', time: '11:00 - 18:00' },
      { day: 'Sábado', activity: 'Clasificación', time: '16:00 - 17:00' },
      { day: 'Domingo', activity: 'Final', time: '13:00' },
    ],
    circuitImage: 'https://placehold.co/600x400.png',
    circuitImageHint: 'race circuit',
  },
  {
    id: 'tcpm',
    category: 'TCPM',
    categoryFullName: 'TC Pista Mouras',
    Icon: CarFront,
    circuitName: 'Autódromo Roberto Mouras',
    location: 'La Plata, Buenos Aires',
    date: '2024-08-18T12:00:00-03:00',
    schedule: [
      { day: 'Viernes', activity: 'Entrenamientos', time: '10:00 - 17:00' },
      { day: 'Sábado', activity: 'Clasificación', time: '15:00 - 16:00' },
      { day: 'Domingo', activity: 'Final', time: '12:00' },
    ],
    circuitImage: 'https://placehold.co/600x400.png',
    circuitImageHint: 'track corner',
  },
  {
    id: 'tcpk',
    category: 'TCPK',
    categoryFullName: 'TC Pick Up',
    Icon: Truck,
    circuitName: 'Autódromo Roberto Mouras',
    location: 'La Plata, Buenos Aires',
    date: '2024-09-08T13:40:00-03:00',
    schedule: [
      { day: 'Viernes', activity: 'Entrenamientos', time: '12:00 - 16:00' },
      { day: 'Sábado', activity: 'Clasificación', time: '15:30 - 16:30' },
      { day: 'Domingo', activity: 'Final', time: '13:40' },
    ],
    circuitImage: 'https://placehold.co/600x400.png',
    circuitImageHint: 'pickup truck race',
  },
  {
    id: 'tcppk',
    category: 'TCPPK',
    categoryFullName: 'TC Pista Pick Up',
    Icon: Truck,
    circuitName: 'Autódromo Roberto Mouras',
    location: 'La Plata, Buenos Aires',
    date: '2024-09-08T12:20:00-03:00',
    schedule: [
      { day: 'Viernes', activity: 'Entrenamientos', time: '11:00 - 15:00' },
      { day: 'Sábado', activity: 'Clasificación', time: '14:30 - 15:30' },
      { day: 'Domingo', activity: 'Final', time: '12:20' },
    ],
    circuitImage: 'https://placehold.co/600x400.png',
    circuitImageHint: 'truck racing',
  },
];
